export const META_PROPERTY_ALTERNATE_SCRIPT = 'alternate-script'
export const META_PROPERTY_AUTHORITY = 'authority'
export const META_PROPERTY_BELONGS_TO_COLLECTION = 'belongs-to-collection'
export const META_PROPERTY_COLLECTION_TYPE = 'collection-type'
export const META_PROPERTY_DISPLAY_SEQ = 'display-seq'
export const META_PROPERTY_GROUP_POSITION = 'group-position'
export const META_PROPERTY_IDENTIFIER_TYPE = 'identifier-type'
export const META_PROPERTY_META_AUTH = 'meta-auth'
export const META_PROPERTY_ROLE = 'role'
export const META_PROPERTY_SOURCE_OF = 'source-of'
export const META_PROPERTY_TERM = 'term'
export const META_PROPERTY_TITLE_TYPE = 'title-type'
export const META_LINK_REL_ACQUIRE = 'aquire'
export const META_LINK_REL_ALTERNATE = 'alternate'
export const META_LINK_REL_MARC21XML_RECORD = 'marc21xml-record'
export const META_LINK_REL_MODS_RECORD = 'mods-record'
export const META_LINK_REL_ONIX_RECORD = 'onix-record'
export const META_LINK_REL_RECORD = 'record'
export const META_LINK_REL_VOICING = 'voicing'
export const META_LINK_REL_XML_SIGNATURE = 'xml-signature'
export const META_LINK_REL_XMP_RECORD = 'xmp-record'
export const META_LINK_PROPERTY_ONIX = 'onix'
export const META_LINK_PROPERTY_XMP = 'xmp'
export const MANIFEST_PROPERTY_COVER_IMAGE = 'cover-image'
export const MANIFEST_PROPERTY_MATHML = 'mathml'
export const MANIFEST_PROPERTY_NAV = 'nav'
export const MANIFEST_PROPERTY_REOMTE_RESOURCES = 'remote-resources'
export const MANIFEST_PROPERTY_SCRIPTED = 'scripted'
export const MANIFEST_VG = 'svg'
export const SPINE_PROPERTY_PAGE_SPREAD_LEFT = 'page-spread-left'
export const SPINE_PROPERTY_PAGE_SPREAD_RIGHT = 'page-spread-right'

export const A11Y_CONFORM_TO_IRI_A =
  'http://www.idpf.org/epub/a11y/accessibility-20170105.html#wcag-a'
export const A11Y_CONFORM_TO_IRI_AA =
  'http://www.idpf.org/epub/a11y/accessibility-20170105.html#wcag-aa'
export const A11Y_CONFORM_TO_IRI_AAA =
  'http://www.idpf.org/epub/a11y/accessibility-20170105.html#wcag-aaa'
